name: Safety

on:
  push:
    branches: 
      - udit-dev-branch
      - main 


jobs:
  safety_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install safety
        run: pip install safety
      - name: Run safety check
        run: safety check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

