name: Security check - Bandit

on:
   push:
     branches: udit-dev-branch


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '2.7.17', '3.7.9' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} 

    steps:
       - name: Checkout PyTorch
         uses: actions/checkout@master
       - name: Security check - Bandit
         uses: ./
         with:
          python_version: ${{ matrix.python-version }}
          project_path: .
          ignore_failure: true

       - name: Security check report artifacts
         uses: actions/upload-artifact@v1
      # if: failure()
         with:
          name: Security report
          path: output/security_report.txt
