name: Security check - Bandit

on:
   push:
     branches: udit-dev-branch


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: [ '3.7.9' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} 

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Security check - Bandit
         uses: jpetrucciani/bandit-check@master
         with:
          python_version: ${{ matrix.python-version }}
          args: '--skips=test_*.py'
          project_path: .
          ignore_failure: true
       - name: Security check report artifacts
         uses: actions/upload-artifact@v1
      # if: failure()
         with:
          name: Security report
          path: output/security_report.txt
